name: KeySmith
options:
  bundleIdPrefix: com.auroravitalis
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"

settings:
  base:
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "5.9"

targets:
  KeySmith:
    type: application
    platform: iOS
    sources:
      - path: KeySmith
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        PRODUCT_BUNDLE_IDENTIFIER: com.auroravitalis.keysmith
        PRODUCT_NAME: KeySmith
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    dependencies:
      - target: KeySmithKeyboard

  KeySmithKeyboard:
    type: app-extension
    platform: iOS
    sources:
      - path: KeySmithKeyboard
      - path: KeySmith/Models/PasswordGenerator.swift
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSExtension_NSExtensionPointIdentifier: com.apple.keyboard-service
        PRODUCT_BUNDLE_IDENTIFIER: com.auroravitalis.keysmith.keyboard
        PRODUCT_NAME: KeySmithKeyboard
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    info:
      path: KeySmithKeyboard/Info.plist
      properties:
        CFBundleDisplayName: KeySmith
        NSExtension:
          NSExtensionAttributes:
            IsASCIICapable: false
            PrefersRightToLeft: false
            PrimaryLanguage: en
            RequestsOpenAccess: true
          NSExtensionPointIdentifier: com.apple.keyboard-service
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).KeyboardViewController
    # no extra dependencies needed
